version: '3'

services:
  ngnix:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: ngnix
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./requirements/nginx/certs:/etc/nginx/certs:ro

    networks:
      - inception_network
    container_name: nginx
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"
    
networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/mariadb
      o: bind
