version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-srandria.42.fr}
      - DB_NAME=${MYSQL_DATABASE:-wordpress}
      - DB_HOST=mariadb
      - DB_USER=${MYSQL_USER:-wpusr}
      - DB_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - wordpress_data:/var/www/wordpress
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/credentials.txt:/run/secrets/credentials.txt:ro
    expose:
      - "9000"
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wpuser}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    expose:
      - "3306"
    
networks:
  inception:
    driver: bridge
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/wordpress
      o: bind
