version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-srandria.42.fr}
      - DB_NAME=${MYSQL_DATABASE:-wordpress}
      - DB_HOST=mariadb
      - DB_USER=${MYSQL_USER:-wpusr}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - REDIS_HOST=redis
    volumes:
      - wordpress_data:/var/www/wordpress
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/credentials.txt:/run/secrets/credentials.txt:ro
    expose:
      - "9000"
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wpuser}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    expose:
      - "3306"
  ftp:
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    image: ftp
    container_name: ftp
    networks:
      - inception
    restart: unless-stopped
    environment:
      - FTP_PASSWORD_FILE=/run/secrets/ftp_password
      - FTP_USER=${FTP_USER:-ftpuser}
    volumes:
      - ../secrets/ftp_password.txt:/run/secrets/ftp_password:ro
      - wordpress_data:/var/www/wordpress
    ports:
      - "21:21"
      - "20:20"
      - "40000-40010:40000-40010"
  redis:
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - redis_data:/data
    expose:
      - "6379"
  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "8080:8080"
  portainer:
    build:
      context: ./requirements/portainer
      dockerfile: Dockerfile
    image: portainer
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    ports:
      - "9000:9000"
    

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/wordpress
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/redis
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/redis
      o: bind


