version: '3'

services:
  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/wordpress

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
    networks:
      - inception
    container_name: nginx
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wpuser}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
    networks:
      - inception
    expose:
      - "3306"
    
networks:
  inception:
    driver: bridge
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/wordpress
      o: bind
